name: Build latest Harfbuzz
inputs:
  release:
    description: "Harfbuzz release"
    required: false
    default: "8.1.1"
runs:
  using: "composite"
  steps:
    - name: Setup harfbuzz cache
      id: cache-harfbuzz
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: harfbuzz-${{inputs.release}}
        key: harfbuzz-${{inputs.release}}
    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.job }}-${{ runner.os }}-${{ runner.arch }}
    - name: Prepare
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install \
          gcc \
          gobject-introspection \
          gtk-doc-tools \
          libcairo2-dev \
          libfreetype6-dev \
          libgirepository1.0-dev \
          libglib2.0-dev \
          libgraphite2-dev \
          libicu-dev \
          ninja-build \
          pkg-config \
          python3 \
          python3-setuptools
    - name: Install Python Dependencies
      shell: bash
      run: sudo pip3 install fonttools meson==0.56.0 gcovr==5.0
    - name: Download and unzip
      if: ${{ steps.cache-harfbuzz.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        wget https://github.com/harfbuzz/harfbuzz/archive/refs/tags/${{inputs.release}}.zip
        unzip ${{inputs.release}}.zip
    - name: Build
      if: ${{ steps.cache-harfbuzz.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        cd harfbuzz-${{inputs.release}}
        ccache --version
        meson setup build \
          -Dauto_features=enabled \
          -Dchafa=disabled \
          -Dgraphite=enabled \
          -Doptimization=2 \
          -Db_coverage=true \
          -Dragel_subproject=true
        meson compile -Cbuild
    - name: Build
      shell: bash
      run: |
        cd harfbuzz-${{inputs.release}}
        sudo meson install -Cbuild
        sudo ldconfig

