name: Build latest Harfbuzz
inputs:
  release:
    description: "Harfbuzz release"
    required: false
    default: "6.0.0"
runs:
  using: "composite"
  steps:
    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.job }}-${{ runner.os }}-${{ runner.arch }}
    - name: Prepare
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install \
          gcc \
          gobject-introspection \
          gtk-doc-tools \
          libcairo2-dev \
          libfreetype6-dev \
          libgirepository1.0-dev \
          libglib2.0-dev \
          libgraphite2-dev \
          libicu-dev \
          ninja-build \
          pkg-config \
          python3 \
          python3-setuptools
    - name: Install Python Dependencies
      shell: bash
      run: sudo pip3 install fonttools meson==0.56.0 gcovr==5.0
    - name: Setup Meson
      shell: bash
      run: |
        ccache --version
        meson setup build \
          -Dauto_features=enabled \
          -Dchafa=disabled \
          -Dgraphite=enabled \
          -Doptimization=2 \
          -Db_coverage=true \
          -Dragel_subproject=true
    - name: Download
      shell: bash
      run: wget https://github.com/harfbuzz/harfbuzz/archive/refs/tags/${{inputs.release}}.zip
    - name: Unzip
      shell: bash
      run: unzip ${{inputs.release}}.zip
    - name: Build
      shell: bash
      run: |
        cd harfbuzz-${{inputs.release}}
        meson compile -Cbuild
        sudo meson install -Cbuild

